### ISSUE TITLE
big images cannot be scanned succesfully, in the first attempt.

### ISSUE THREAD

**Issue by ontheway16** [undecaf/zbar-wasm#1]
Hello, I am trying different images with the codepen demo site, but have a problem.
Files of very big images (40-50 MP) are returning with no results '[ ]', in the first try.

Same image, second attempt from same file, all is well, all qrcodes are correctly identified. If I resize down to something around 2000px width, instant result comes, no problems even in the first attempt with that file.

What might be causing this ?

**Comment by undecaf** [comment]
Does zbar-wasm behave in the same way when you post the images to the demo site: https://undecaf.github.io/barcode-detector-polyfill/example/ ? This would eliminate effects caused by running the demo in Codepen.

If the behavior is the same then please copy and post the output from the dev tools console of your browser.

Having the images available on some public place (Dropbox etc.) would also be helpful for testing if the QR codes do not contain sensitive information.

**Comment by ontheway16** [comment]
> 

Thank you for the fast response, I tried and first image returned with null.
But, second and following images (all same size, big) created no problems (They were completely new to browser, not scanned formerly). Also, initially failed image succeeded in the second attempt. 

Here is a dropbox link of a sample image.
https://www.dropbox.com/s/nfi0vhzu7bvkqq9/test_image2.jpg?dl=0

**Comment by undecaf** [comment]
Fixed in version 0.9.11. Thanks @ontheway16 for pointing this out so that I could fix a stupid mistake.

**Comment by ontheway16** [comment]
One last thing, can you please kindly update the following link, with the applied update?

https://cdn.jsdelivr.net/npm/@undecaf/zbar-wasm/dist/index.js

Thank you !

**Comment by undecaf** [comment]
https://cdn.jsdelivr.net/npm/@undecaf/zbar-wasm/dist/index.js already points to the most recent release (0.9.11). After a new release has been published, it always takes some time for this link to get updated, and I cannot influence this process.

Specifying the release as part of the link (such as in https://cdn.jsdelivr.net/npm/@undecaf/zbar-wasm@0.9.11/dist/index.js) allows accessing any release immediately after it has been published, and no ambiguities can arise later when new (possibly incompatible) releases get published.

**Comment by ontheway16** [comment]
Does this demo link already at latest, as of now ?
https://undecaf.github.io/barcode-detector-polyfill/example/

Since I just checked, it failed to read in the first attempt (same image size at above link).
Second attempt with same image file, succeeded.

**Comment by undecaf** [comment]
@ontheway16: Updated [barcode-detector-polyfill](https://www.npmjs.com/package/@undecaf/barcode-detector-polyfill) to 0.9.11 as well, barcode detected now on first scan also in large images.
