### ISSUE TITLE
How to bundle zbar.wasm in a module project?

### ISSUE THREAD

**Issue by iBobik** [undecaf/zbar-wasm#11]
I develop [capacitor-community/barcode-scanner](https://github.com/capacitor-community/barcode-scanner/pull/276) and want to make it support off-line, so zbar.wasm needs to be included.

I successfully included it in a dist of this module:
```
  plugins: [
    copy({
      targets: [
        { src: 'node_modules/@undecaf/zbar-wasm/dist/zbar.wasm', dest: 'dist' },
      ]
    })
  ],
```

But when I use barcode-scanner in my project (`npm i "@capacitor-community/barcode-scanner@../barcode-scanner"` for local development) and build it, resulting dist does not include zbar.wasm file.

I checked [example-bundled](https://github.com/undecaf/barcode-detector-polyfill/tree/master/example-bundled), but this seems not intended for use in the module project (and also it is for old rollup 2).

Or it is really necessary to ask module's users to bundle zbar.wasm themself? How to make zbar-wasm to require it correctly then?

Thank you for your help.

**Comment by undecaf** [comment]
@iBobik Apologies for my late reply, I have been on vacation. I cannot provide a simple solution to this issue; I can only present my findings, hoping that they are helpful.

### CommonJS targets

The CommonJS build of `@undecaf/zbar-wasm` (i.e. the WASM/CommonJS glue logic generated by Emscripten) does not allow to detect any dependency on `zbar.wasm` (that filename is just an innocuous string literal), so IMHO all CommonJS projects will have to use a copy plugin for `zbar.wasm`. Nevertheless, I hope someone can prove me wrong.

### Rollup 3

I have not been able to make Rollup bundle `zbar.wasm` automatically, no matter which target environment. [`@rollup/plugin-wasm`](https://github.com/rollup/plugins/tree/master/packages/wasm) did not help either.

### Webpack 5

The WASM/ESM glue logic in `@undecaf/zbar-wasm` contains the instruction `new URL('zbar.wasm', import.meta.url)` which makes Webpack bundle `zbar.wasm` automatically  whenever it includes the _ESM build_ of `@undecaf/zbar-wasm`.
Unfortunately, making Webpack select the ESM build presently requires an `resolve.alias` entry which is only a small improvement over a copy plugin. See [this gist](https://gist.github.com/undecaf/94da934cfe6b8b06def3c50e0e3d552c) for example Webpack configurations.

### Next steps for zbar-wasm

The `export` conditions in `package.json` of `@undecaf/zbar-wasm` 0.9.16 are quite a mess, so I understand that Webpack has to be forced to select the ESM build of `zbar-wasm` over the CommonJS build.
But even after setting the `export` conditions as [documented for Webpack](https://webpack.js.org/guides/package-exports/#conditions), I was not able to make Webpack select the ESM build of `@undecaf/zbar-wasm` when appropriate.
As I am not too familiar with Webpack, any hints would be welcome.

**Comment by fspoettel** [comment]
I don't know if this is helpful for this specific issue, I apologize if it is not. As `vite` uses `rollup` under the hood, I figured I post a working config for it:

```ts
import { defineConfig } from "vite";
import wasm from "vite-plugin-wasm";

export default defineConfig({
  plugins: [wasm()],
  // config below makes the build work.
  optimizeDeps: {
    exclude: [
      "@undecaf/zbar-wasm"
    ]
  },
});
```

this works both in dev and prod, where the build puts out `wasm` and properly externalizes `module`.

```
vite v4.4.8 building for production...
[plugin:vite:resolve] Module "module" has been externalized for browser compatibility, imported by "<snip>/node_modules/@undecaf/zbar-wasm/dist/main.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
✓ 1302 modules transformed.
dist/index.html                                    0.49 kB │ gzip:  0.32 kB
dist/assets/index-d465abb6.js                     17.22 kB
dist/assets/zbar-d779f39f.wasm                   239.02 kB
dist/assets/index-b4c9e5df.css                    11.99 kB │ gzip:  3.02 kB
dist/assets/__vite-browser-external-b25bb000.js    0.03 kB │ gzip:  0.05 kB
dist/assets/index-dbe8b31c.js                    186.93 kB │ gzip: 61.10 kB
✓ built in 1.32s
```

**Comment by borracciaBlu** [comment]
Similar issue here using `next`.

with `0.9.15` worked like a charm.
After the update to `0.9.16` i've got the following error:

```
./node_modules/@undecaf/zbar-wasm/dist/main.js
Module not found: Can't resolve 'module'
``` 

Please consider i did use the import syntax
```
import { scanImageData } from '@undecaf/zbar-wasm';
```

instead if i use require:
```
const { scanImageData } = require('@undecaf/zbar-wasm');
```

i've got:
```
./node_modules/@undecaf/zbar-wasm/dist/main.cjs
Module not found: Can't resolve 'fs'
```

i can create a project to reproduce if you need

**Comment by undecaf** [comment]
Thank you @fspoettel !

@iBobik Plugin `@web/rollup-plugin-import-meta-assets` can include `zbar.wasm` as an asset in Rollup 3. The module referencing `@undecaf/zbar-wasm` must be an ES module, and the plugin needs option `warnOnError: true` to be set. I provided a [pull request](https://github.com/modernweb-dev/web/pull/2422) so that this option is no longer needed.

**Comment by undecaf** [comment]
@iBobik zbar-wasm v0.10.0 should resolve this issue.

PTAL at [`tests/rollup.config.js`](https://github.com/undecaf/zbar-wasm/blob/master/tests/rollup.config.js) which demonstrates several ways of bundling zbar-wasm with Rollup; I hope that one of them is suitable for your situation.

Closing this, please feel free to re-open.

**Comment by iBobik** [comment]
Thank you. I will work on it at the end of month.

3. 9. 2023 15:46:28, undecaf ***@***.***> napsal:

**Comment by iBobik** [comment]
@undecaf I am looking into it, but found I will probably need you to update also barcode-detector-polyfill.
