### ISSUE TITLE
The barcode type DataMatrix is not supported

### ISSUE THREAD

**Issue by grahn195** [undecaf/zbar-wasm#13]
Can you add support for the datamatrix code?

Thank you!

**Comment by undecaf** [comment]
zbar-wasm delegates scanning to the code of [ZBar Bar Code Reader](https://github.com/mchehab/zbar) compiled to WebAssembly. Therefore, zbar-wasm can only scan what is supported by the ZBar Bar Code Reader.

Please open an issue at [ZBar Bar Code Reader](https://github.com/mchehab/zbar) if you need additional barcode formats to be supported.
