### ISSUE TITLE
[BUG] WebAssembly.Module doesn't parse at byte 1227: invalid opcode 192, in function at index 28

### ISSUE THREAD

**Issue by indykoning** [undecaf/zbar-wasm#17]
**Describe the bug**

On Ipad safari the webassembly script fails to compile due to the following error:
```
failed to asynchronously prepare wasm: CompileError: WebAssembly.Module doesn't parse at byte 1227: invalid opcode 192, in function at index 28
```

**To Reproduce**

Opening the example on an ipad and uploading an image file of a barcode https://undecaf.github.io/zbar-wasm/example/ will result in "Source not ready" with the specified error above.

Or else the environment in which the behavior occurs needs to be specified:
 - Which target environment (Node/browser/other)? IOS Safari (on Iphone/Ipad, Macbook works fine)
 - Which type of modules (ESM/CommonJS/other)? CommonJS Version 0.10.1, 0.9.16, 0.9.15, 0.9.14

**Comment by undecaf** [comment]
Which iOS version and Safari version have you been using for the example?

**Comment by indykoning** [comment]
Unfortunate for debugging, but fortunate for me the Ipad had updated to IOS 16.7.5 which has resolved the issue.
I'm guessing it was most likely the older browser not supporting some of the opcodes used in the wasm file

I will close this for now as i am no longer able to reproduce the issue

**Comment by erickedji** [comment]
@undecaf  We still get production logs about this issue, from browsers as recent as Safari 16.6 on iPhone 16.7.2 (released in July 2023).

I found pointers here for making the webassembly module compatible with a wider set of browsers: https://github.com/emscripten-core/emscripten/issues/19121

**Comment by undecaf** [comment]
@erickedji  According to [this table](https://webassembly.org/features/), Safari should support WASM sign-extension since 14.5 on iOS. I just verified the [example](https://undecaf.github.io/zbar-wasm/example/) to work also under Safari 16.2 which also is older than the version you mentioned.

Therefore it seems unlikely that sign-extension operations are the cause for your production logs. Since I do not wish to disable all new WASM features only to be on the safe side, could you please be more specific on what exactly is being logged?

**Comment by undecaf** [comment]
@erickedji I think that the error message does not indicate that there is anything wrong with the WASM file: `zbar.wasm` v0.9.16 _does_ contain a data section that starts at offset 100282 (`0x0187BA`), and it is indeed 138735 (`0x021DEF`) bytes long, and it extends up to the the last byte of the WASM file at offset 239016 (`0x03A5A8`), as can be seen in the [WebAssembly Code Explorer](https://wasdk.github.io/wasmcodeexplorer/) (`EF BB 08` is 138735 in [unsigned LEB128 encoding](https://en.wikipedia.org/wiki/LEB128#Unsigned_LEB128)):

![Bildschirmfoto_2024-04-25_00-37-01](https://github.com/undecaf/zbar-wasm/assets/7375196/e149cfa1-5b8e-421a-a917-3141dd890bfc)

The [WASM validation utility (`wasm-validate`)](https://webassembly.github.io/wabt/doc/wasm-validate.1.html) reports the file to be valid, too, using only `sign-extension` as an advanced feature:
```
wasm-validate --disable-mutable-globals --disable-simd --disable-bulk-memory --disable-saturating-float-to-int --disable-multi-value --disable-reference-types zbar.wasm
```

Therefore I think that your error message could be the result of too little memory for Safari, or maybe even a bug in Safari 16.6

**Comment by erickedji** [comment]
Thanks for the investigation @undecaf
I checked the logs and found other Safari 16.6 visitors without that issue (only one visitor with the issue), so we can keep this closed.
