### ISSUE TITLE
[BUG] On IOS Safari Iphone 12 - after background/sleep mode reactivation changes camera to fisheye

### ISSUE THREAD

**Issue by opicron** [undecaf/zbar-wasm#18]
**Describe the bug**

When using the example on IOS Safari Iphone 12 initially the default hi-res rear camera is used. Leaving the web scanner on in background causes a different camera (fisheye) to be selected. Making scanning nearly impossible.

**To Reproduce**

Visit demo through Github

- Put browser in background by flicking it out of screen (slide finger from bottom of screen to top)
- Turn off screen with button on right side of iphone
- Wait 10 seconds
- Turn on screen
- Put browser in foreground

**Expected behavior**  

Expected behaviour would be to have the same camera active after returning from background/sleep.

**Screenshots**  

| Initial Cam  | Cam after BG |
| ------------- | ------------- |
| <img src="https://github.com/undecaf/zbar-wasm/assets/472432/9c5385e6-b428-4308-9725-81672909a8b2" height="400">  | <img src="https://github.com/undecaf/zbar-wasm/assets/472432/cc86b035-c4b2-446a-98ea-e7a6edb54086" height="400">  |

**Comment by undecaf** [comment]
IMHO this cannot be a bug of zbar-wasm because this module does not control the camera in any way, i.e. it can neither switch beween front and back camera nor prevent this.

**Comment by opicron** [comment]
Ah, I think in main.js this needs to be adressed:

navigator.mediaDevices.getUserMedia({ audio: false, video: { facingMode: 'environment' } })

In here we can determine exact deviceID. I will improve and report back when it works.

**Comment by opicron** [comment]
By selecting the last camera in the available devices most phones return the correct enviroment camera. As such: 

```
            // List cameras and microphones.
            navigator.mediaDevices.enumerateDevices()
                .then((devices) => {
                    devices.forEach((device) => {
                        if (device.kind == 'videoinput') {
                            deviceCam = device.deviceId;
                        }

                    });
                    constraints = {
                        audio: false,
                        video: {
                            width: {
                                min: 1280,
                                ideal: 1920,
                                max: 2560,
                            },
                            height: {
                                min: 720,
                                ideal: 1080,
                                max: 1440
                            },
                            deviceId: deviceCam
                        }
                    }
                    navigator.mediaDevices.getUserMedia(constraints)
                        .then(stream => {

                            videoContainer.srcObject = stream

                        })
                        .catch(error => {
                        })
                    detectVideo(true);
                })
                .catch((err) => {
                    console.error(`${err.name}: ${err.message}`);
                });
```

**Comment by undecaf** [comment]
Thank you @opicron for your investigation!

I would not feel well, however, including this workaround in the example since I could not find any specification that guarantees that the last device represents the environmental camera.

Instead, I am thinking about replacing the line
```javascript
navigator.mediaDevices.getUserMedia({ audio: false, video: { facingMode: 'environment' } })
```
with
```javascript
navigator.mediaDevices.getUserMedia({ audio: false, video: { facingMode: { exact: 'environment' } } })
```
which _requires_ rather than just _requests_ a device facing the environment ([specified here](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints#constraindomstring)).

Unfortunately, I do not have an iPhone available for testing. I would appreciate very much if you could test this idea; if this works then I would like to modify the example accordingly.

**Comment by opicron** [comment]
Yes, this was my first approach. But that didnt work out unfortunately.

**Comment by opicron** [comment]
If we add `facingMode: { exact: 'environment' }` to the above example code it might be even more consistent.

**Comment by undecaf** [comment]
Unfortunately, in Safari/iOS this will still only give us _some_ camera facing the environment, not necessarily the high-resolution camera.

In recent WebKit browsers one could add the [`zoom` capability](https://github.com/WebKit/WebKit/blob/272b9bed22c24464ce9e3862066291558badba97/Source/WebCore/Modules/mediastream/MediaDevices.cpp#L232) to the `MediaTrackConstraints`, this should prevent fisheye cameras from being selected (only guessing, not tested).

**Comment by opicron** [comment]
Going to check this too. Thanks for lead.
