### ISSUE TITLE
[Enhancement] Allow specifying the URL of the WASM file

### ISSUE THREAD

**Issue by fidian** [undecaf/zbar-wasm#23]
**Describe the bug**

I use Vite to build and bundle my project. In order to get the WASM file as a part of my build, I copy it to my `site/` folder and it is treated as a static asset. When the imported code attempts to load the WASM file, it uses a path that is deeply nested, such as `/.vite/deps/undecaf-zbar-wasm/zbar.wasm` because the script is served from that location for development. In production, the file would be built into `/assets/index-HASH.js`, so it would look for `/assets/zbar.wasm`.

**To Reproduce**

I'm using Vite, TypeScript, and it appears that the ESM version is being used.

**Expected behavior**  

Having a way to specify the URL to the WASM file would be ideal instead of having it automatically build a URL based on the imported file.

This is already done with [zbar-wasi](https://github.com/myisaak/zbar-wasi) and I was hoping that something similar could be done with this build.

To work around this issue, I custom-compiled zbar-wasm's output to remove terser, then manually modified the path of "zbar.wasm" and changed it to "/zbar.wasm".

**Comment by undecaf** [comment]
@fidian For details, please see [here](https://github.com/undecaf/zbar-wasm?tab=readme-ov-file#loading-zbarwasm-from-a-custom-location) in the README file.

**Comment by fidian** [comment]
Awesome, thank you for adding this!

**Comment by id1945** [comment]
@undecaf  How to use for typescript version lower than 5.1.6 ?

**Comment by undecaf** [comment]
@id1945 Please open a new issue describing what is happening when the TS version is below 5.1.6 and providing a minimal working example for this situation.
