### ISSUE TITLE
[BUG] library not being recognized/provided by vite

### ISSUE THREAD

**Issue by RhuanPrado** [undecaf/zbar-wasm#24]
### Describe the bug

I created react project with vite typescript.
My problem's is using the library [@undecaf/zbar-wasm](https://github.com/undecaf/zbar-wasm).

### BarcodeScanner.jsx
```javascript
import { scanImageData } from "@undecaf/zbar-wasm"

const scanBarcode = useCallback(async () => {

                const context = canvasRef.current.getContext("2d")
		context.drawImage(videoRef.current, 0, 0, canvasRef.current.width, canvasRef.current.height)
		const imageData = context.getImageData(0, 0, canvasRef.current.width, canvasRef.current.height)
		try {

			const symbols = await scanImageData(imageData)
			if (symbols.length > 0) {
				const barcode = symbols[0].decode()
				const quality = symbols[0].quality
				updateScannedBarcodes(barcode, quality)
			}
		} catch (err) {
			console.error("Error scanning image data:", err)
		}
	}, [updateScannedBarcodes, isScanning])
[...]

```

### My vite.config.ts
```javascript
import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"
import path from "path"

export default defineConfig({
	plugins: [
		react(),
	],
	resolve: {
		alias: {
			src: path.resolve(__dirname, "src"),
		},
	},
	server: {
		port: 3000,
	},
	assetsInclude: ['**/*.wasm'],
});

```
### Errors
```
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
(anonymous) @ @undecaf_zbar-wasm.js?v=fd05e335:210
Promise.then (async)

failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0

Error scanning image data: RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -sASSERTIONS for more info.
    at P (@undecaf_zbar-wasm.js?v=fd05e335:70:14)
    at @undecaf_zbar-wasm.js?v=fd05e335:103:59

```

In my investigation I learned that vite does not provide .wasm .

![Screenshot from 2024-05-28 18-41-33](https://github.com/vitejs/vite/assets/37555050/14d345d5-dd26-44df-9268-2f715f83600b)

### My solution for the problem, which is not the preferred:
```javascript
import { scanImageData, setModuleArgs } from "@undecaf/zbar-wasm"

setModuleArgs({
	locateFile: (filename) => `https://cdn.jsdelivr.net/npm/@undecaf/zbar-wasm@0.11.0/dist/${filename}`
})
```
### The .wasm is provided this way, but not through the library loader :
![Screenshot from 2024-05-28 18-54-20](https://github.com/vitejs/vite/assets/37555050/0604291b-b3cd-417f-abf3-59ccd4775424)

**Comment by undecaf** [comment]
This message:

> failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0

indicates that Vite is not loading a WASM file but an HTML file. Possible reasons are discussed in [this issue](https://github.com/WebAssembly/spec/issues/1031).

Unfortunately I cannot give advice on how to configure Vite as I am not familiar with this environment. In any case, this is not a bug of `zbar-wasm`.

**Comment by RhuanPrado** [comment]
I wanted to know if I was doing something wrong, thank you for replying and also alerting me to the problem I've experienced and registering it for others.

[wasm-based library not being recognized/provided by vite #17334](https://github.com/vitejs/vite/issues/17334)

[#8427](https://github.com/vitejs/vite/issues/8427)

**Comment by RhuanPrado** [comment]
Another way to solve this problem is to add it to vite.config.ts:

```javascript

export default defineConfig({
	// others configs ...
	
	optimizeDeps:{
		exclude:["@undecaf/zbar-wasm"]
	}// add this config
});
```

**Comment by RhuanPrado** [comment]
Another way to solve this problem is to add it to vite.config.ts:

```javascript

export default defineConfig({
	// others configs ...
	
	optimizeDeps:{
		exclude:["@undecaf/zbar-wasm"]
	}// add this config
});
```
[Solution](https://github.com/vitejs/vite/issues/8427#issuecomment-1911157180)
