### ISSUE TITLE
Configure custom ZBarScanner instance

### ISSUE THREAD

**Issue by degorov** [undecaf/zbar-wasm#25]
`scanImageData`, `scanGrayBuffer`, `scanRGBABuffer` all can take `ZBarScanner` as last argument. Is it possible to create custom `ZBarScanner` that looks only for QR codes? The idea is to get performance gain in situations where we don't need to support all barcode types.

**Comment by undecaf** [comment]
`ZBarScanner` can be configured to look only for certain symbol types; the [description](https://github.com/samsam2310/zbar.wasm/wiki#disable-unused-symbol-type) can be found in the wiki of the [predecessor project](https://github.com/samsam2310/zbar.wasm).

**Comment by degorov** [comment]
Thanks a lot, the answer is right there.
