### ISSUE TITLE
Paused when failed to detect unsupported code type.

### ISSUE THREAD

**Issue by fengdh** [undecaf/zbar-wasm#3]
https://output.jsbin.com/nidonin
Please try my live sample based on zbar.wasm, which will detecting QR or other supported code types continuously. Just open it on your iPhone or Android phone then point & shoot. It outperforms other pure JavaScript QR detection libraries. 

But sometime my live sample stops to detect from new video feed, even once it recognized correctly just seconds ago. I figured out one pattern to reproduce this bug:

1. Point to some supported QR code/Barcode, worked fine to recognize all of them continuously.
2. Include some unspported barcode in video feed, suddently it stops to recognize any more.
3. (Sometime it seems that a failed try on supported code type will also cause consequent failure).
4. (Misleading in title: not pause of live sample, but once worked well, sometime suddently stop to recognize from further new video feed. Reload will restart recognition again. Is it any way to recycle/recover consequent detection programtically?)

From https://github.com/mebjas/html5-qrcode, I printed out many different types of QR code and Barcode for testing.

![image](https://user-images.githubusercontent.com/4262924/186333767-eb935607-1b02-4d83-9f82-bb9123ef2c8e.png)

**Comment by undecaf** [comment]
I could reproduce the effect in a desktop browser. Your code assumes that the `points` array contains at least three points. This is not guaranteed. If the `points` array contains fewer points then the line
```javascript
return {raw: s, data: s.decode(), b: {left: tl.x, right: br.x, top: tl.y, bottom: br.y} };
```
causes an exception and the scanning process stops. PTAL at the console in your browser devtools.

Closing as this is not related to `zbar-wasm`.

**Comment by fengdh** [comment]
Thanks for your reply. And many thanks for your libraries.
