### ISSUE TITLE
TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by xulihang** [undecaf/zbar-wasm#6]
I am encountering the following error trying to integrate zbar-wasm in a Quasar + Vite project:

```js
main.js:15  Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at n (main.js:15:3357)
    at main.js:15:7714
    at Generator.next (<anonymous>)
    at main.js:15:283
    at new Promise (<anonymous>)
    at t (main.js:15:28)
    at main.js:15:7667
```

**Comment by xulihang** [comment]
Here is the test project: https://github.com/tony-xlh/barcode-reading-benchmark/tree/f3bd1295151fac891d8847b45bf838b5c2291852

**Comment by xulihang** [comment]
I am now using it via CDN by adding the script in the index.html file.

**Comment by xulihang** [comment]
It works.

**Comment by undecaf** [comment]
Glad to hear that, so I am closing this issue.
