### ISSUE TITLE
Issue with utf-8

### ISSUE THREAD

**Issue by id1945** [undecaf/zbar-wasm#7]
<i>The image is confidential, so it should be removed</i>

**Comment by undecaf** [comment]
Hmm... the raw bytes of the QR code are decoded by the browser's [TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) according to the selected character encoding, so there is not much that I can do about false decoding.

On the other hand, are you sure that the QR code is UTF-8 encoded? I googled and found several Vietnamese character encodings.

**Comment by undecaf** [comment]
Let me explain in more detail: `zbar-wasm` delegates decoding the raw bytes contained in the QR code to the text displayed as `rawValue` to the [`TextDecoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) built into each browser. By default, the `TextDecoder` uses UTF-8 encoding, but a [several other encodings are available](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/encoding).

If the text is not what is expected then I see two possible reasons:

1. A bug in the browser's `TextDecoder` -- unlikely but can be verified by trying whether a different browser produces the same text.
2. The text in the QR code is in an encoding different from UTF-8, so decoding the raw bytes as UTF-8 will likely yield a wrong result.
    Therefore I am kindly asking you again whether it can be confirmed that your QR code is actually UTF-8-encoded. The producer of the QR code should be able to provide this information.

**Comment by undecaf** [comment]
I copied your expected text, pasted in into an [online QR generator](https://www.qr-code-generator.com/) and obtained this QR code: 
![QR code generated from expected text](https://github.com/undecaf/zbar-wasm/assets/7375196/63fbfd02-b748-4e56-9a83-01c73d107302)

Scanning this QR code yields the following (correct) result:
![Result of scanning the generated QR code](https://github.com/undecaf/zbar-wasm/assets/7375196/87af7729-a4e0-4549-8b7e-c26709e346f1)

This indicates that the text in your QR code is most likely not UTF-8-encoded.

**Comment by id1945** [comment]
@undecaf 
### But this site works with my qrcode

https://www.imgonline.com.ua/eng/scan-qr-bar-code.php

![350967356_1290468401874512_7479876211832692424_n](https://github.com/undecaf/zbar-wasm/assets/40824445/b223e58a-6a97-4132-b075-724cc07e67fe)

![350956564_780577416944815_125115878265378873_n](https://github.com/undecaf/zbar-wasm/assets/40824445/43a1dce1-6e02-48fb-b9c2-a212d5196027)

**Comment by undecaf** [comment]
Hmmm... the `BarcodeDetector` built into mobile Chrome also reads that code correctly.

Please give me some time to look into that.

**Comment by id1945** [comment]
@undecaf 

I really hope you get this fixed soon. Since I am developing a library for Angular `ngx-scanner-qrcode` based on yours.
And finally, please allow me to delete the photo of my citizenship card in the comment above.
Waiting to hear from you soon ^^!

**Comment by undecaf** [comment]
@id1945 Your [original qr code](https://user-images.githubusercontent.com/40824445/242818542-16d00646-d343-44fe-8118-219b7e864b6e.jpg) can be read correctly by configuring `zbar-wasm` to return binary data and delegating text decoding to the native `TextDecoder` e.g. like so:
```typescript
import { ZBarConfigType, ZBarImage, ZBarScanner, ZBarSymbolType } ...;

const scanner = await ZBarScanner.create();
scanner.setConfig(ZBarSymbolType.ZBAR_NONE, ZBarConfigType.ZBAR_CFG_BINARY, 1); // <-- important
scanner.scan(image);
const symbols = scanner.getResults();
```
However, in order to read [the code that I generated](https://user-images.githubusercontent.com/7375196/242853049-63fbfd02-b748-4e56-9a83-01c73d107302.png) correctly, the `scanner.config()` statement has to be **omitted**.

Thus, with a particular setup, either one or the other QR code can be read correctly but not both.

This appears to be one of the [peculiarities](https://github.com/NaturalHistoryMuseum/pyzbar/issues/95) of the [ZBar bar code reader](https://github.com/mchehab/zbar) on which `zbar-wasm` is based. Unfortunately, there is nothing that I can do about that.

**Comment by id1945** [comment]
@undecaf  Thank you very much. I've also tried and it doesn't work at all. It is still a headache for me.

**Comment by pascalschoeni** [comment]
@undecaf jschardet (https://www.npmjs.com/package/jschardet) may help:

```
const detectedCharSet = jschardet.detect(Buffer.from(symbol.data))
const text = foundQr.decode(detectedCharSet.encoding)
```

**Comment by id1945** [comment]
@undecaf  🥇 
I will soon delete all the `QR code` containing my personal data here. I will give you another `QR code` image with the above error please wait for me. @@

**Comment by id1945** [comment]
@undecaf :rofl::rofl::rofl::rofl:
Luckily for me! 🙏
I found these websites that generate the error QRcode as we are discussed above. Below is the QRcode that I created. You can also create your own in `Vietnamese` language. 

https://qrplanet.com/#text
https://qrcode.tec-it.com/en/Raw

`Thôn Hoan Trung, Chiến Thắng, Bắc Sơn, Lạng Sơn`

![Capture-001](https://github.com/undecaf/zbar-wasm/assets/40824445/badc44c3-01a9-4acf-a878-c874a566af82)
