### ISSUE TITLE
after 15 june this package giving an error 

### ISSUE THREAD

**Issue by aditiroygithub** [undecaf/zbar-wasm#8]
'Error: Corrupted zip: missing 48 bytes.\n    at ZipEntries.readEndOfCentral (D:\\codebase\\iona\\onboarding-dbmodel\\node_modules\\jszip\\lib\\zipEntries.js:243:19)\n    at ZipEntries.load (D:\\codebase\\iona\\onboarding-dbmodel\\node_modules\\jszip\\lib\\zipEntries.js:255:14)\n    at D:\\codebase\\iona\\onboarding-dbmodel\\node_modules\\jszip\\lib\\load.js:48:24'

**Comment by undecaf** [comment]
I do not see how this issue is related to this package, please clarify

**Comment by undecaf** [comment]
Closing as unrelated to this package.
